{
 "title": "Autometrics Service-Level Objectives (SLOs)",
 "tags": [ "autometrics" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "success_rate_objective",
    "query": {
     "query": "label_values({__name__=~\"function_calls_count(:?_total)?\"}, objective_name)"
    }
   },
   {
    "name": "latency_objective",
    "query": {
     "query": "label_values(function_calls_duration_count, objective_name)"
    }
   },
   {
    "name": "success_rate_objective_percentile",
    "query": {
     "query": "label_values({__name__=~\"function_calls_count(:?_total)?\", objective_name=\"$success_rate_objective\"}, objective_percentile)"
    }
   },
   {
    "name": "latency_objective_percentile",
    "query": {
     "query": "label_values(function_calls_duration_bucket{objective_name=\"$latency_objective\"}, objective_percentile)"
    }
   },
   {
    "name": "latency_objective_latency_threshold",
    "query": {
     "query": "label_values(function_calls_duration_bucket{objective_name=\"$latency_objective\"}, objective_latency_threshold)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "`$success_rate_objective` Success Rate Objective (Target: $success_rate_objective_percentile%)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "success_rate_objective"
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n  sum(\n    rate(\n      {\n        __name__=~\"function_calls_count(:?_total)?\", \n        objective_name=\"$success_rate_objective\", \n        result=\"error\"\n      }[$__range])\n    ) or on() vector(0)\n  ) / (\n    sum(\n      rate(\n        {\n          __name__=~\"function_calls_count(:?_total)?\", \n          objective_name=\"$success_rate_objective\"\n        }[$__range]\n      )\n    ) > 0\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30-day Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n  sum(\n    rate(\n      {\n        __name__=~\"function_calls_count(:?_total)?\", \n        objective_name=\"$success_rate_objective\", \n        result=\"error\"\n      }[$__range]\n    )\n  ) or on() vector(0)\n) / (\n  sum(\n    rate(\n      {\n        __name__=~\"function_calls_count(:?_total)?\", \n        objective_name=\"$success_rate_objective\"\n      }[$__range]\n    )\n  ) > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate by Function",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum by (function, module, version, commit) (\n    rate(\n      {\n        __name__=~\"function_calls_count(:?_total)?\", \n        objective_name=\"$success_rate_objective\", \n        result=\"error\"\n      }[$__rate_interval]\n    )\n    * on(instance, job) group_left(version, commit) (build_info or on (instance, job) up)\n  ) > 0\n) / (\n  sum by (function, module, version, commit) (\n    rate(\n      {\n        __name__=~\"function_calls_count(:?_total)?\", \n        objective_name=\"$success_rate_objective\"\n      }[$__rate_interval]\n    )\n    * on(instance, job) group_left(version, commit) (build_info or on (instance, job) up)\n  ) > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "`$latency_objective` Latency Objective (Target: $latency_objective_percentile% ≤ $latency_objective_latency_threshold sec)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "latency_objective"
  },
  {
   "title": "% of requests under ${latency_objective_latency_threshold}s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    rate(\n      function_calls_duration_bucket{\n        objective_name=\"$latency_objective\", \n        le=\"$latency_objective_latency_threshold\"\n      }[$__range]\n    )\n  ) or on() vector(0)\n) / (\n  sum(\n    rate(\n      function_calls_duration_count{\n        objective_name=\"$latency_objective\"\n      }[$__range]\n    )\n  ) > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30-day % of requests under ${latency_objective_latency_threshold}s",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n    rate(\n      function_calls_duration_bucket{\n        objective_name=\"$latency_objective\", \n        le=\"$latency_objective_latency_threshold\"\n      }[$__range]\n    )\n  ) or on() vector(0)\n) / (\n  sum(\n    rate(\n      function_calls_duration_count{\n        objective_name=\"$latency_objective\"\n      }[$__range]\n    )\n  ) > 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of requests exceeding ${latency_objective_latency_threshold}s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  1 - (\n    sum by (function, module, version, commit) (\n      rate(\n        function_calls_duration_bucket{\n          objective_name=\"$latency_objective\", \n          le=\"$latency_objective_latency_threshold\"\n        }[$__rate_interval]\n      )\n      * on(instance, job) group_left(version, commit) (build_info or on (instance, job) up)\n    ) / (\n      sum by (function, module, version, commit) (\n        rate(\n          function_calls_duration_count{\n            objective_name=\"$latency_objective\"\n          }[$__rate_interval]\n        )\n        * on(instance, job) group_left(version, commit) (build_info or on (instance, job) up)\n      ) > 0\n    )\n  )\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}