global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s
rule_files:
  - /etc/config/autometrics-rules.yml
# Prometheus polling metrics from itself
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
# Prometheus polling metrics from your application running in the same network
scrape_configs:
  - job_name: internal-endpoint2
    metrics_path: /metrics
    static_configs:
      # Within a private network over http. 
      # For Northflank and Railway you can find the private network reference in the service settings
      # It will be something like this "service-name:PORT"
      - targets: ['example-service:8000'] 
    # For a real deployment, you would want the scrape interval to be
    # longer but for testing, you want the data to show up quickly
    scrape_interval: 120s

# Note: if you want to push your metrics towards Prometheus for example with the Otel collecor,
# you don't need to define a scrape endpoint.
# just make sure in the Dockerfile to enable the remote write endpoint